-- ================================================================
-- INSYTE: 01_users_roles.sql
-- Oracle 23ai Security Architecture & DCL Configuration
-- Run as SYSDBA against FREEPDB1
-- ================================================================

ALTER SESSION SET CONTAINER = FREEPDB1;

-- 1. Create Application Administrator (Schema Owner & ETL)
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER INSYTE_ADMIN IDENTIFIED BY "AdminSecurePassword2026!" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW,
      CREATE SEQUENCE, CREATE SYNONYM, CREATE PROCEDURE, CREATE TRIGGER TO INSYTE_ADMIN;

-- 2. Create Reporting Analyst Role (Least-Privilege Security)
BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE INSYTE_ANALYST_ROLE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1921 THEN RAISE; END IF;
END;
/

-- 3. Create Restricted Analyst User
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER INSYTE_ANALYST IDENTIFIED BY "AnalystSecurePassword2026!"';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1920 THEN RAISE; END IF;
END;
/

GRANT CREATE SESSION TO INSYTE_ANALYST;
GRANT INSYTE_ANALYST_ROLE TO INSYTE_ANALYST;

-- Grant selective read-only permissions
GRANT SELECT ON INSYTE_ADMIN.CUSTOMERS TO INSYTE_ANALYST_ROLE;
GRANT SELECT ON INSYTE_ADMIN.PRODUCTS TO INSYTE_ANALYST_ROLE;
GRANT SELECT ON INSYTE_ADMIN.ORDERS TO INSYTE_ANALYST_ROLE;
GRANT SELECT ON INSYTE_ADMIN.ORDER_ITEMS TO INSYTE_ANALYST_ROLE;
GRANT SELECT ON INSYTE_ADMIN.REVIEWS TO INSYTE_ANALYST_ROLE;
GRANT SELECT ON INSYTE_ADMIN.REVIEW_MEDIA TO INSYTE_ANALYST_ROLE;
GRANT SELECT ON INSYTE_ADMIN.TRANSACTION_ADJUSTMENTS TO INSYTE_ANALYST_ROLE;
GRANT SELECT ON INSYTE_ADMIN.ETL_AUDIT TO INSYTE_ANALYST_ROLE;

-- Private synonym setup for reporting user
-- Allows INSYTE_ANALYST to query 'sales_orders' instead of 'INSYTE_ADMIN.ORDERS'
CREATE OR REPLACE SYNONYM INSYTE_ANALYST.sales_orders FOR INSYTE_ADMIN.ORDERS;
CREATE OR REPLACE SYNONYM INSYTE_ANALYST.catalog_products FOR INSYTE_ADMIN.PRODUCTS;

PROMPT [INSYTE] Security roles and least-privilege users successfully established.
